
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "c809d1ad8ff0f699280c735b524d215768c242970ad1abbb94e7265a5c5cead50cd67ca95d43939fac2453bafcafec0dc44acef78e6afd013df4494a40f4178400"
genesis_address_str = "2gCKbJzkVYZA3EvsYosexq9jdvP3iQ8iFBv"
blockchain_pubkey_str = "03b427d19f1059fb8cfe9ab11f65c55a3b27799f411f49c397e0f9a1ccd7fc3659"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
genesis_coin_volume = 200e12
default_connections = [
    "192.243.100.192:6660",
    "167.114.97.165:6660",
    "198.245.62.172:6660",
    "198.100.144.39:6660",
    "94.23.56.111:6660",
]
peer_list_url = "http://cantdoevil.com/blockchain/peers.txt"
port = 6660
web_interface_port = 6420
# web_interface_addr = "127.0.0.1"
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "PrivateNess"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "HNESS"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
max_coin_supply = 2e8
initial_unlocked_count = 50
unlock_address_rate = 5
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 10
distribution_addresses = [
"2j3MwXbaaHpDqjNuukERpmqZbAGwbw6fTSS",
"2jYb4Jds2sJezvz3FwpRNQeSitKAWjSJ8pD",
"2bA94FuKvhuCawifn1bWztcepUQyzndMjLB",
"2fZDYnJ69FAfxCfimSyUWFJvAivPphyck3K",
"29JNY4HkTVc2joHHiuKVF161hj8qbc12VPF",
"4jjoqHJ1sV6uDfox5HAZoEzZKS5Mu1FNJx",
"4Q7TQJp5C5XkHrGFRXTnfoCvLBwXf37kSW",
"M9dydziJPzpbtTtbzPpGP6jorHvDrBfGQo",
"2izDrbVEaKN1SckX9C9Kg8DNKJK3eLaArjB",
"2X5gQTfPfsJA2wKCxvZuZg9jVuUZo5RjyAP",
"UutJDsJ29YPyvEVzdCJEeWnogMLABVLwto",
"A9nYFU6enJiHykqdR1mFWYnyEmFy8yqsTm",
"foDLvhbdBFb81vBLgeyqwMifaGcyuQiSoT",
"1FWNCWekTUHX6APwtiZeRDDNUH4jazdSZk",
"bAXTwJdpDujr6im8Yz4KDA3Sw3MLDp51xr",
"jeLBEndkWszBC5BsAcT7K6gpthi4Yj4KH9",
"22EtftoCKRanprJ1JJeAGtAAy1eW8k51GqE",
"6LGccR2JWFYr9z9aTYgQ1uHeFidQzAX97j",
"t6LrQzqgPuzyi33UiCUikBa8QtKKfMsv3z",
"eiySG8Lk3jCUNbckFckC9uQqSkTERQBmws",
"2eWvCFGexJsTe4rkQ3ATGF61NjsxLFSEm2z",
"2U3JVM5YbmVSTKaJ1bMws2RtVbTiQi9QaKD",
"2GKMuBW9JUqM8YwacCVMKEGtXzGkG3ehXCH",
"2itFPqMKvYgBWXVn9fxFccxMusK671Sjf2C",
"2G5YM4Du2v83z1RaJLfnNT31x32P748GmmY",
"SWraMixJ7vd7UFMPzkT85HcVQbF5wnn6Ds",
"fSfg2ZGD1m3rQttKmrG7CFxMP86Jh5kpH3",
"pvYbeSjBiavws4rPLTAMuAZgfcSWWHjuw5",
"K4NsguTkvepN3Bj7Kj8jh12xAebgdsDURm",
"ykCNZgbczXhpFovfXgLkYAYN8dUFTXvw3r",
"2LrCgdcaJJoMiGppisGb9SRKdyppGRYhSTo",
"2Bxj8aPYme2wfJ9Y69EJVVxRqFeC1DK9LtM",
"9KugfaPG9nFoC4nRdfCbQzFnTZuQy3PMVo",
"24GSWASKNC8iGiXZNtYDjvs4FTQtCdQi9ZL",
"2YYi2nUDrkkT2e668QTv6MX5zpZ32fJsypJ",
"2FdjELNwJxyv4tkrLcmfzSB6LsTUjbWheqD",
"qi75a1Ee6yDFFNWoN6741wVwYrWi2Si8W9",
"2iywkoG7kSKaWcQ9rvvgRJ4F1DePhXJz3RK",
"2aebJZimmmEaRoTRA4iwD6Tg4t96vUontMA",
"2JjjYGgmNqXNCR58EUc2tbBq3dkA23rnMtp",
"qNina7YBKsszZ9bBJBgCQ7aXC3jBPGCxbt",
"UywAq9MQVsCEPHKKVHkzUYf2LxEr2dyFSM",
"bcu1bwjSKu3FtM3THm6HARpvtrgcSCRLah",
"2jU1aPGByscwnWkNx8erAeGqbfmR3gQ5ear",
"H9uNvVU7PKSvqCKaTjHbK8R3s6jRpA1kHq",
"3edQ5YPrG6hLR7k76aBQ6t9hgbSFcCv692",
"2J94Zh9KhXNseQ99GU5XTbH16RnpAFXKXHJ",
"2EtM79JtjUNRLTm6t2egNwEyvnJ6h24LaQa",
"qMBiVRakgnnUTiAfoKJZAQKhJGMm8xnxkX",
"oekyLfUX5KRKyASzFiH7DoGwfSYaPzAHGE",
"ZwFjpdaLoexDBC1oTZPjWNgs8CLKUD2CMh",
"xQ69Jp1Su1QwTzL3UV8TQbswF1xSwtnfnA",
"HP4AeD2a2ezg2yQa1V6GnWjmqm6Fd76UXj",
"29ddDBFFAVMuzjifhGm2yFp9TQ672zPHGNz",
"2iWgh3DgbC1tAyRYycRBTDnwMJ9kZ1Y6oY9",
"2HAetHFPK9iBuSsT9XiKaDRAzKymT38BwpM",
"2QSpUBPFZv8wNT6MxMRLwhyZgYJFw6BGsr7",
"hnSWUaDBp4jL98dJekCPr67b29MsuTyDY3",
"2KYvJxKbatcMwnTVKiXFrYAF11kjepbpG1J",
"2MsrmxGMoYD6Y2ZG8BNKH1vf16kQkLhE1TV",
"cBBZhmSvsqik6MBUkVKqrhkYS5vBPCgdEF",
"YGigaaofZhL7YhLiprJudVrcjzcFkLdhxA",
"2RffRKv7jUQekCEELCteL9KYWqGFQm4RFMC",
"Kih4tecVXQ3PaFPaPrhYBa3bMMm9KfPdsC",
"ZjT9o5GwuVi6ZkAUtwCBr5MYuGCsszfgNG",
"ZMfpjJC9fWGMZMGHeWb1aQ78rQM81f2KSE",
"U22tnzuDaqJ4FLakpHuYJ1xSbDvL2Mc1Vk",
"E6x78b9fCUuYNp5T3DeJM53V2iYNFHrUrr",
"N6uh4LRFMuo27fyZGinSU1LMmTiJmvnyNG",
"54nqgayArFUU6cCgVxgc44Kja7ijPhmecV",
"Ux1kHP5yAFy77d3yV98aQFoLHPdV7zjS1E",
"Cec8RyjsNv1pLVYBY5Pbr4FQ33kNPGVuQP",
"2gYTg6ob4LW95Au4BdCL7jwb43ypLwnvauA",
"2mjphwEh29tVPiWP3NAod6ePsqo1EU9n6Hw",
"9iSTXrPvJSiJi4rxgtdLj3qzxssusfpKAr",
"rruR8TUCa4yShzzcHXj6TLkzVfEvt58FwK",
"21o5NL9Js5v36GFM6EbjpxzvxoLGXsRoseQ",
"2FMwDpdy5e8Prz6LEKtQD3T7CsTkfDSQdY",
"cgNZtA6biadrCNz4GZtVnhC7Sa69BZJiYE",
"EXQ5ue1wBk1XehE1QRDJNKhRvZNfZK18pZ",
"3S9113vhMM5cW1g5Esq5A9v63RpUYmyy1B",
"Y3J3ek7YnmD4DABUyXHVx9wHgua7Kjdcyi",
"2GVCCTiTBQbm2BgW11kRgNhsDSugexMWV2F",
"24yFEQ4ju5UzzwuVH4x7rPrr7cecRyX7nsT",
"21qbe5pUP7Ttjr4gaDZfQLFApiTpDcU6114",
"2c1v4CdUXsYzULJjFcX9mzW9N1DG6X4tm3o",
"XBuZJtc3pBSkg3h1JwfMoMc4XjbSYsBcD2",
"2GNYgQ5Sx6jTdddtkcV33bJSFqvWuVE77NA",
"iHR591ineTMZ7VPPducZTd6UB7NKH2xrAn",
"2gpe4r1Pg2HhaTsHqMSH19pWPctPxfysrAQ",
"2TqnqpfxS8rd19kLrFsPDWQsUGRhscFdPDV",
"2XZfeJpupnKhJ6dSuyxZLPh3Xg1Vf1m33aX",
"RRHfFq8NmndL9s3EVG5kdCrE2r5xTFTZsk",
"wnF2WDLx5LqTiJepv7mRzWJE9k49z1SNes",
"G9gnWXmsWNAESmwjBMgyM4iKbjJwSqYLte",
"x3YXV6YQBuHbiJXDXB9uCgtaLkocUgNDXe",
"6c3BdZvkvrV8zcrpHyuWvJj2fuCzGEj37k",
"2aHNSaSetJTFedr13XJgmXvNQFzoGzy4bi9",
"s66ykX6KPsc5iWYKhsX1tFD1j25QBtg1um",
"2gWzNCkwHUhEXFP3ec9kJMoQMhW1NdrHMwK",
"W9iB4tifonbFBNyfCq3CfJJpknhu2q7nxP",
"sBXxTyiP2smoQ3w2Hz3ekYAu3cuQiZ64V8",
"25SCbksb7aUowGQ6cnycHE2MgB3j3nqsGFw",
"2j4uPyqV9BY6xPUz34Uss9eFbPb9xuAFBV",
"G1cMp4zLiUgYcspy6BPfwuMU87xWktWqw8",
"wvh8eyF4Z2TcZTSxLT6PCavyXYGekAcd6X",
"2VmhWWYjtQvBiAqP5DBAndgzuVfma46Js5G",
"sJE1bdTpZb8e9Cd7Rw2MvbwJUDxgJchhTT",
"2QpUdVABZRQ2retXnSgCVietV8N7qdmLmQj",
"NnJbPUDKDdxQ3NUTtstPnMhxqWwhtWzSHr",
"TssZHK6NBL3PgXVh3VxBSCqTfoZ1heCPKU",
"2RVZ34M5W4eD3bjRDeKvuTQFm9dRtQhahmp",
"2RG2pczv2hA2R5nMVo4v8evA25L4RU3Kz8h",
"216Jt3J5755GCNSu34Jz2dJyM1zKgubVbra",
"2CrW7jnJ78kbisi4f3PWbf4YdGqAP5gY51j",
"umES4VBafHDNQYG1rLSpryJydsU114R85n",
"6fRkMJEwqnB44joD1Jjf4QfqHybdgr1Ts5",
"2E2RLceUdgG2YiUjYgK8SbS9xMVTVmQmTVu",
"Z6xKKpuSChCakFMTZiDYGoz23nZzwuKUq5",
"23Zf3noSQnPpPM4y4mWPbjPEqrqCeaBM2kS",
"DDnYE2ExhXefCqDVgu9ts69zzxBcR9kCkt",
"2eRDpbKMLi7dZu3qaaLFsV3YsUr3jqtV4F5",
"2f2ecNhsm5sazPqKZ2tfBFyZ6G2QgojbNbS",
"mrzhtnKh8LfS7mNh2LYTRGNGcVLYTwvcwA",
"GGc2iEbVXyxsHLJ5yBSD7yGkqgV3CXGK7h",
"2ekiJL5rgva5TTysTKBRzKpX92tUinXt1a",
"2JWzu83UE6wvqsZ6PxmDjTSjTnyUuabaYTW",
"ozHMXkEvhDCbHHRRNaf8ufNzyex8zhpe6A",
"nk2WV9zaYz86pnZ4cTGYChJYxiVZ2gsdYe",
"eg3sPPME2FNCVm8RXTZw89dtuJ4SdfZmaJ",
"25hAoGuBKzPgpUfRQcrR2CESr7mBUFCFzLq",
"WrkJuYWfqcjE8k5WRWqggHEb68k7r5zAVg",
"3fySjoETtyMGfu4xVTsyYVw5RcYbTaV9rJ",
"sZ7L4y3Kh5Rc1JspaVB7pLmXgzuq4Kp9BT",
"2Vkwk8StBeWMdgEzYSihukATZJZcRRK1PXX",
"259ri2QWtQw6WGkcddXinN5y2CHAQmN8zEd",
"2VjBxEkMzdGpnuCcCmFrrbicKpwjsgYqrZ8",
"LXNZDKhkkWdPdziPUeiXciKQverJEFpudX",
"V9hKwsKxUPFS9ZCWriepBNr6E7VsrN2JGY",
"28mByXuTzRTvyYh3bhfzq32DXdSLFwGFtSa",
"ynqrRgxBkii9r8W3N9BFVjRSYDNMmyWTY9",
"rjSK8UfWdyaPb7teLJVbpYnyeoVxH45Gk3",
"ykBnEfU8ihHfA6WR3CCoJfGQrRpsMysdhL",
"YgGy5Aeu7tkDM5EFuthiJAWV8AevkPDxyZ",
"2UFdq3Rus9wLvRVwxT1L4pmKDso6wH7p3da",
"2WvRGH2rWaLxV5JHt5eoFfo5UkHTJSiwVsJ",
"kE9r5GAzr1n38uX913sUNLA9j7WvghVZP3",
"2ZJjZcBwoHpC23dbeNjmaxkDKu1V16Spoyt",
"WtVz3yTmBYq9HC7cu9U8NoNhW4Y6QizHDB",
"ys2RFZbVvpLBvp4MCQc4Cymu6ymqXX9TXD",
"2XPioBcBAtuxqAKrMHGNmiHmzHx1e16Atvk",
"2gDoLJTRc4YmYcR8mo4VNKczXhzq6nYTgCd",
"iKE4d2YXPsu463dMGQkXemKAaSLNnTHSAp",
"dLStMT7BTBrtAdast4qTj8khxBtayCoBaU",
"21CEvePWZRBXEatFgQ6H5yaS1qZVpdN5BCM",
"2FZkRyfbKtxFQf5xLhrg8VmKGoeTXSo7tcD",
"X1aSVcKCAHHF1BZPyAvyFaiUhN8TrbZVik",
"2dE3MHsAzwGhrJqtiLpBnWPRHsiAqGfMsnZ",
"hdtsCuUBdRMf8bu7xdHcUtQaCSRH1tnQ5u",
"2XKBZHJkP6JqBSEjwr4cp8udJCaPV4ae3Gt",
"2agWTsyZaEVg2n9EyH1uxs7GCRAVZ69t4hA",
"2dy3gbqNsh6vRJXDifEQXHvgLA7RgzfpfU",
"smezoKAD3rKm61pKhQGEZY4UtoYEhXniGt",
"2ReWFm2Z2JqVMynhYSp86345bNUeJKqYhpJ",
"29TX2MxD5wo9k3XhrHRCGNQ9qKLb9WGAm8k",
"PQSz1dKdjy3GbSGUFx6tY66rhnutqYxaQ1",
"TaAK1HRarxn12qSp8ug3CoXmYRDtidTPuu",
"d6wiATw4SaG7D84tnwVucNjSo7Rxe5AaBS",
"2e3yGvUpmgwJuR9PbKrWWye5wKbMD3Vx2LD",
"2mrn2ffcKujYcUii7BjA2nWTSJnc9jjX14k",
"uJgA8GQqmpXWnJ9HNTEA8KARVCX1RMfZXX",
"2Kmwvi42f69MKb7MPPLBbqLovYJBH5UrYiS",
"jQBahqEzACzvCBww7NPQTmN4Hbv2gynFmW",
"GpJcDARZ4gHAF78awNpe2r5JhGP54C9h7R",
"J98y1jS8MByLcb6LihwtQ9Z47Mow3YgDEL",
"2GL4eXfLyphpXyBBULkPEbAyAGPjJBJLzxo",
"JcmsRQnZRUaT5srZjzHhf96eJSEk87GmMm",
"2a5ZGLXfQaABJpVpL3WKnXV3vKMowY3TJ6M",
"2VTcpZ1V8mJerjZWPe7aDLib1GyV5TLtwVA",
"g4kZqzLAD5KxGFHZjuaxaBUVtMYAeaJqBd",
"2WiLDqvAjrmY6qHjatZqRohGFH7bjKkFnbj",
"rGTzzcLUjAi5AQzU9shW59TAXsvkApKykR",
"9JG3m5FQwAf9aCmstkMrtZMwGXbAmdXmaD",
"LeKKc4i2L1xyVYHr4GiE5ZRP3os39suv49",
"BzEw2Kg1wxqrAqqup88GbfnEozQrFVX7hY",
"onLACPu6BkoKnuQ3WUmxQo7WUSkyL8niiz",
"2YLskdvv1HCY3EwFcUksi3z17jsz6JjZHnA",
"jNDAn3nVih82R7th5mGDgbS7qpi5LXXjBu",
"dCyNZXtVmRSkrYPGWkVs7Ws6nDCD76Be1x",
"2FxQvurnM2r3JPhGqtHaGKdifMyRvVjdA85",
"F8BHzbioo49BCbLESWDsF18yjCWp3PtqWr",
"ncCtvaicQrRrfxzmCNjgoacCDhg3DBdS6U",
"2SHd8mRch1VB4FrcUJHMHZ5xyZFQbRNcH2j",
"26VNkzThUtMMMXTpUy2HmZTvkyWfc7i7D3i",
"sbeGopscD5qVe6hK5CLeLrZqjyQfATCKrn",
"BCybxdVsHWfR1c7NSEeeBDVgWawnKdC73C",
"Bgs39UtptcFSi77jSFuZdv7hdnXHvNBJBY",
"2bcH1fNnCMRpauUUhitQoVo722GmQ1S6VXr",
"CiNv5cJZnZrEw43mqgnFMBbHiRRuD3oajF",
"t39s3oMwPEU18FvUSnZWkibi5gfpPCRuqG",
]
